### PR TITLE
Resolve a bunch of snyk vulnerabilities

### PR DESCRIPTION
**Pull request by markjm**
Update the base image and some of the add-on dependencies to resolve a bunch of CVEs identified by Snyk. I have tested AWS and file storage types with node16, and dont see anything that would prohibit using node 16 for the other storage types (though did not test myself)

### CODE REVIEW

**Review by alexmcode — APPROVED** [review]
Hey @markjm thanks for your time and contribution! We appreciate it.

The changes look good. I've also run them locally and all seems good. I do have 2 questions for my own curiosity mainly:
- In order to fix the CVEs, was it necessary to update to `node:16`?
- How did you used Snyk in order to discover the vulnerabilities? Maybe we can use it to improve out OS repos :)

**Comment by markjm** [comment]
Hi @alexmcode - to answer your questions:

1. Was it necessary to update to node:16? Yes, but in a round-about way. Essentially, there were a bunch of deb vulnerabilities in the underlying alpine image. Since node@14 is out of support, the base images are not updated to pull in those patched underlying changes. Since 16 is LTS and is being built more regularly, the underlying alpine vulnerabilities are getting patched out in the base image. If, for example, we could just update the underlying alpine image backing node@14, that would work too, but requires much more to do.
2. My place of employment had a bunch of monitoring and whatnot with partners like Snyk - unfortunately no valuable knowledge or tools I can share out here :/

**Comment by alexmcode** [comment]
> Hi @alexmcode - to answer your questions:
> 
> 1. Was it necessary to update to node:16? Yes, but in a round-about way. Essentially, there were a bunch of deb vulnerabilities in the underlying alpine image. Since node@14 is out of support, the base images are not updated to pull in those patched underlying changes. Since 16 is LTS and is being built more regularly, the underlying alpine vulnerabilities are getting patched out in the base image. If, for example, we could just update the underlying alpine image backing node@14, that would work too, but requires much more to do.
> 2. My place of employment had a bunch of monitoring and whatnot with partners like Snyk - unfortunately no valuable knowledge or tools I can share out here :/. Just figured id do my part to lift up the ecosystem tools we use instead of just patching internally :)

Thanks for the clarifications and thanks again for taking the time to contribute!

**Comment by alexmcode** [comment]
Also, @markjm although the code looks good we are checking/testing other file storage to make sure everything is working. If all is good we can merge this

**Review by konstrybakov — APPROVED** [review]

**Pull request merged**
