### PR TITLE
server.js: always respond with raw content for some user agents

### PR DESCRIPTION
**Pull request by williamboman**
Note: I haven't been able to test this _at all_. (prob not functional as is)

### CODE REVIEW

**Comment by FichteFoll** [comment]
I don't like this kind of "implicit magic". It's a guarantee for weird, unpredictable behavior (to those not knowing about the trick). There might also be cases where you would *want* to receive the html would have to modify your user agent to do so.

If you want to download the actual file, just feed the RAW url.

**Comment by williamboman** [comment]
IMO it makes a lot of sense to do this, feels pretty natural as well (again, IMO :smile:). I also can't think of a single reason one would want to fetch the HTML output seeing as the paste data is not included in that response at all.

**Comment by filipechagas** [comment]
Thank you for contributing!

I don't think it makes sense for the app to decide which endpoint the client should be using, though. It already has the `raw/:id` endpoint for when the user needs a raw response. I would assume that if a client is requesting the `document/:id` endpoint it's actually expecting to get the html page as result.

**Comment by williamboman** [comment]
Oh wow I had forgotten about this one.

savingprivateryan-ww2

**Comment by filipechagas** [comment]
This app was recently acquired by Toptal and we're now trying to catch up on some old stale contributions. I'm it took so long for us to get here 😄

**Pull request closed without merging**
