### PR TITLE
Added support for the latest MongoDB Driver

### PR DESCRIPTION
**Pull request by JoCat**
Starting from version 3 of MongoDB Driver, you need to separately specify the connection address and select the table using `client.db('db_name')`

### CODE REVIEW

**Comment by ririko5834** [comment]
works good, but please fix also this

```
(node:549) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:549) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
```

**Comment by JoCat** [comment]
ok, even though this is a simple warning)

**Comment by JoCat** [comment]
I'm not good at Mongo yet, but I sort of fixed

**Comment by ririko5834** [comment]
Ty, Also are haste entries auto removed after 30 days from latest visit from mongodb?

**Comment by JoCat** [comment]
Haven't tested yet, just recently installed 😏

**Comment by ririko5834** [comment]
@JoCat I have problem, can you please help me? When i try to add haste i am getting this in console:
```
(node:1212) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:1212) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
error: error persisting value to mongodb code=79, codeName=UnknownReplWriteConcern, name=MongoWriteConcernError, n=1, nModified=0, upserted=[index=0, _bsontype=ObjectID, 0=95, 1=212, 2=138, 3=220, 4=160, 5=11, 6=64, 7=193, 8=56, 9=152, 10=59, 11=159], _bsontype=Timestamp, low_=14, high_=1607764700, t=8, _bsontype=ObjectID, 0=127, 1=255, 2=255, 3=255, 4=0, 5=0, 6=0, 7=0, 8=0, 9=0, 10=0, 11=8, ok=1, code=79, codeName=UnknownReplWriteConcern, errmsg=No write concern mode named 'majorityw=majority' found in replica set configuration, _bsontype=Timestamp, low_=14, high_=1607764700, _bsontype=Binary, sub_type=0, position=20, 0=186, 1=239, 2=7, 3=215, 4=50, 5=165, 6=54, 7=179, 8=75, 9=206, 10=12, 11=215, 12=39, 13=231, 14=216, 15=99, 16=137, 17=8, 18=138, 19=216, _bsontype=Long, low_=3, high_=1602492855, _bsontype=Timestamp, low_=14, high_=1607764700
```

**Comment by JoCat** [comment]
> Ty, Also are haste entries auto removed after 30 days from latest visit from mongodb?

Doesn't seem to work

**Comment by ririko5834** [comment]
@JoCat Yes it does not work for me, I setuped expire in config.json file. Can someone fix the problem?

**Comment by JoCat** [comment]
@ririko5834 Honestly, I have no idea how it works

**Comment by xlnd47** [comment]
@JoCat  ConnectionName is not being used, so all entries will go to database "test"

**Comment by xlnd47** [comment]
@ririko5834 did you insert it under storage inside the config file like this?
```json
"storage": {
    "type": "mongo",
    "connectionUrl": "mongodb+srv://username:password@cluster0.xxxx.mongodb.net",
    "connectionName": "dbname",
    "expire": 2592000
  },
```

**Comment by JoCat** [comment]
i am using the following config:
```
"storage": {
    "type": "mongodb",
    "connectionUrl": "mongodb://localhost:27017",
    "connectionName": "haste"
  }
```
Everything works for me correctly

**Comment by JoCat** [comment]
> > Ty, Also are haste entries auto removed after 30 days from latest visit from mongodb?
> 
> Doesn't seem to work

@ririko5834 I am an idiot, I did not register expire in the config 🤣

**Comment by anondev-sudo** [comment]
Make sure to close the connection after reading/writing data in mongodb.

It generates large amount of connections 
image
image

Then you cant view or make new pastes when you reach 500 connections limit:
image

@JoCat Can you PR this?

**Comment by JoCat** [comment]
> Can you PR this?

Yes, I can see in a couple of hours, I'll just be at home

**Comment by JoCat** [comment]
@anondev-sudo i fixed the error with the connection limit, now the connection is closed after executing the request

The only thing that I do not like this approach a little. Callback hell is crazy. I tried to rewrite the class here (https://github.com/JoCat/haste-server/commit/84338fd81db05b941f4b09f1120cdbd8efa79176), although I need to modify the code a little more

**Comment by vpn** [comment]
Thanks for that @JoCat, your fix worked for me.

**Pull request closed without merging**
