### PR TITLE
Add base url support

### PR DESCRIPTION
**Pull request by doodadjs**
Hi. A friend of mine asked for help to use your application with another base URL than root. I did it for him and now I'm sharing my changes to the community. There is only two files changed in the front end. The back end has not been touched. Don't forget to clear the cache of the browser before trying if you've already used it (I had this issue).

For the back end, you have to use a proxy server implementing a rewrite of the requested urls. See [http://www.ctrl-alt-del.cc/2014/11/haste-server-base-url-hackpatch.html](http://www.ctrl-alt-del.cc/2014/11/haste-server-base-url-hackpatch.html)

I hope that it will work fine for you.

### CODE REVIEW

**Comment by KingDuckZ** [comment]
What's blocking this PR from being merged?

**Comment by seejohnrun** [comment]
@KingDuckZ @doodadjs I think the requirement to use a proxy server is an issue.  I'd prefer if we could get a solution that would for the server-side as well.  The issue there is that there's currently no data passed between the two layers.  I've started on a branch to do this, but I'm not ready to merge it yet.  If someone else is interested it shouldn't be too difficult to get going, but I don't want to bring in a feature (as much as I appreciate the work here) that's half complete.

Otherwise, I'd be down to take a look this weekend and try to get something that works for both cases.

**Comment by doodadjs** [comment]
@seejohnrun I understand. I wanted to touch less code than possible, but that's not enough.

**Comment by LeCodeCo** [comment]
This works so well for me while proxying via Nginx and I think would be beneficial for others.

**Comment by rubenwardy** [comment]
You should always deploy applications behind a reverse proxy in production

**Comment by filipechagas** [comment]
This is will probably fix https://github.com/toptal/haste-server/issues/156 and fix https://github.com/toptal/haste-server/issues/214

**Comment by IzMichael** [comment]
Any progress on merging this?

**Review by kry008 — APPROVED** [review]
Working changes, tested on Ngnix with `http://base_url/customdir`

**Comment by The-Epic** [comment]
Any update on this?

**Review by filipechagas — APPROVED** [review]

**Pull request merged**
